datadir = "aergo/data"
dbtype = "badgerdb"
enableprofile = false
profileport = 6060
personal = true
authdir = "aergo/auth"
logdir = "aergo/log"

[rpc]
netserviceaddr = "0.0.0.0"
netserviceport = 7845
netservicetrace = false
nstls = false
nscert = ""
nskey = ""
nsallowcors = false

[p2p]
# Set address and port to which the inbound peers connect, and don't set loopback address or private network unless used in local network
netprotocoladdr = ""  # Insert IP address from this machine
netprotocolport = 7846
npbindaddr = ""
npbindport = 7846
# TLS and certificate is not applied in alpha release.
nptls = false
npcert = ""
# Set file path of key file
npkey = "./blockchain/bp.key"
npaddpeers = [  # Insert IP address and BP ID from this machine
]
npdiscoverpeers = true
npmaxpeers = "100"
nppeerpool = "100"
npexposeself = true
npusepolaris= true
npaddpolarises = [
]

[blockchain]
# blockchain configurations
maxblocksize = 1048576
coinbaseaccount = "AmNh2EaWdsLvPY5HaA7vEY5g8cWYeeSbJebo1pEDgC8tNidQFQV3"  # Insert BP Address from this machine
maxanchorcount = "20"
verifiercount = "2"
forceresetheight = "0"

[mempool]
showmetrics = false
enablefadeout = false
fadeoutperiod = 12
verifiers = 4
dumpfilepath = "aergo/data/mempool.dump"

[consensus]
enablebp = true
blockinterval = 5

[monitor]
protocol = ""
endpoint = ""

[account]
unlocktimeout = "60"

[sql]
maxdbsize = 204800 
